import type { Metadata } from "next";
import { Anton, Comfortaa } from "next/font/google";
import "./globals.css";

const anton = Anton({
  subsets: ["latin"],
  display: "swap",
  weight: ["400"],
  variable: "--font-anton",
});

const comfortaa = Comfortaa({
  subsets: ["latin"],
  display: "swap",
  weight: ["600", "700"],
  variable: "--font-comfortaa",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${anton.variable} ${comfortaa.variable}`}>
        {children}
      </body>
    </html>
  );
}
